---
version: "2.3"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - nzbget_data:/config
      - /Volumes/MovieBackup/downloads:/downloads
      #- radar_downloads:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - downloader_network
    cpus: 2
    mem_limit: 3g
    memswap_limit: 3500m
    
  hydra2:
    depends_on:
      - nzbget
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - hydra2_data:/config
      - /Volumes/MovieBackup/downloads:/downloads
      #- radar_downloads:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
    networks:
      - downloader_network
    cpus: .2
    mem_limit: 300m
    memswap_limit: 800m
 
  radarr:
    depends_on:
      - nzbget
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - radarr_data:/config
      - /Volumes/Public/Shared Videos/PlexMedia/Movies:/movies
      - /Volumes/MovieBackup/downloads:/downloads
      #- radar_downloads:/downloads
    ports:
      - 7878:7878
    networks:
      - downloader_network
    restart: unless-stopped
    cpus: .5
    mem_limit: 400m
    memswap_limit: 600m

volumes:
  nzbget_data:
  hydra2_data:
  radarr_data:
  #radar_downloads:
networks:
  downloader_network:
    