---
version: "2"
services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - radarr_data:/config
      - radarr_movies:/movies
      - radarr_client:/downloads
    ports:
      - 7878:7878
    networks:
      - radarr_network
    restart: unless-stopped
    
volumes:
  radarr_data:
  radarr_movies:
  radarr_client:
network:
  radarr_network: