---
version: "2"
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - nzbget_data:/config
      - /Volumes/Public/Radarr:/downloads
    ports:
      - 6789:6789
    restart: unless-stopped
    networks:
      - radarr_network

  hydra2:
    depends_on:
      - nzbget
    image: linuxserver/hydra2
    container_name: hydra2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - hydra2_data:/config
      - /Volumes/Public/Radarr:/downloads
    ports:
      - 5076:5076
    restart: unless-stopped
    networks:
      - radarr_network
 
  radarr:
    depends_on:
      - nzbget
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - radarr_data:/config
      - /Volumes/Public/Shared Videos/PlexMedia/Movies:/movies
      - /Volumes/Public/Radarr:/downloads
    ports:
      - 7878:7878
    networks:
      - radarr_network
    restart: unless-stopped

volumes:
  nzbget_data:
  hydra2_data:
  radarr_data:
networks:
  radarr_network: